// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"time"
)

type Link struct {
	ID          string    `json:"id"`
	TargeNoteID string    `json:"targeNoteId"`
	Description *string   `json:"description,omitempty"`
	CreatedAt   time.Time `json:"createdAt"`
}

type Mutation struct {
}

type Note struct {
	ID          string    `json:"id"`
	Title       string    `json:"title"`
	Content     string    `json:"content"`
	Tags        []string  `json:"tags"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
	Summary     *string   `json:"summary,omitempty"`
	KeyConcepts []string  `json:"keyConcepts"`
}

type Query struct {
}

type Subscription struct {
}

type BackLink struct {
	ID          string    `json:"id"`
	SourceNote  *Note     `json:"sourceNote"`
	Description *string   `json:"description,omitempty"`
	CreatedAt   time.Time `json:"createdAt"`
}

type CreateNoteInput struct {
	Title   string   `json:"title"`
	Content string   `json:"content"`
	Tags    []string `json:"tags"`
}

type SearchResult struct {
	Note      *Note   `json:"note"`
	Score     float64 `json:"score"`
	Reason    string  `json:"reason"`
	MatchType string  `json:"matchType"`
}

type SmartSearchResponse struct {
	Results     []*SearchResult `json:"results"`
	Explanation string          `json:"explanation"`
	Gaps        []string        `json:"gaps"`
	Connection  []string        `json:"connection"`
}

type UpdateNoteInput struct {
	Title   string   `json:"title"`
	Content string   `json:"content"`
	Tags    []string `json:"tags"`
}
